package com.skilledmonster.sakila.model;

// Generated Mar 17, 2013 7:41:54 AM by Hibernate Tools 3.4.0.CR1

/**
 * ActorInfo generated by hbm2java
 */
public class ActorInfo implements java.io.Serializable {

	private ActorInfoId id;

	public ActorInfo() {
	}

	public ActorInfo(ActorInfoId id) {
		this.id = id;
	}

	public ActorInfoId getId() {
		return this.id;
	}

	public void setId(ActorInfoId id) {
		this.id = id;
	}

}
